### ISSUE TITLE
Web UI is unavailable in Firefox - only spinner

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/Vagrantfiles#83]
I've accepted certificate, but then UI doesn't load. Refreshing doesn't help.

![изображение](https://user-images.githubusercontent.com/393741/69332520-e9afd180-0c67-11ea-852a-7c9ee3dc2d8b.png)

This is after manually starting network in #82.

```
[vagrant@adm ~]$ sudo vim /var/log/nginx/access.log
10.0.2.2 - - [21/Nov/2019:11:03:57 +0000] "GET /ui/favicon.ico HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
``` 

error.log is empty.

I've also checked relevant chroma logs, they are empty:
```
[vagrant@adm ~]$ sudo vim /var/log/chroma/http_agent.log
[vagrant@adm ~]$ sudo vim /var/log/chroma/http.log
```

Web debug in Firefox shows "messaging" request doesn't have any headers or reply.

![image](https://user-images.githubusercontent.com/393741/69333241-5e374000-0c69-11ea-948a-80dab798e66c.png)

All of IML services appear to be running normally:
```
  iml-action-runner.service                                                                loaded    active   running   IML Action Runner Service
  iml-agent-comms.service                                                                  loaded    active   running   IML Agent Comms Service
  iml-corosync.service                                                                     loaded    active   running   IML Corosync Service
  iml-gunicorn.service                                                                     loaded    active   running   IML Manager Service
  iml-http-agent.service                                                                   loaded    active   running   IML Http Agent Service
  iml-job-scheduler.service                                                                loaded    active   running   IML Job Scheduler Service
  iml-lustre-audit.service                                                                 loaded    active   running   IML Lustre Audit Service
  iml-mailbox.service                                                                      loaded    active   running   IML Mailbox Service
  iml-plugin-runner.service                                                                loaded    active   running   IML Plugin Runner Service
  iml-power-control.service                                                                loaded    active   running   IML Power Control Service
  iml-realtime.service                                                                     loaded    active   running   IML Realtime Service
  iml-settings-populator.service                                                           loaded    inactive dead      IML Settings Populator
  iml-stats.service                                                                        loaded    active   running   IML Stats Service
  iml-stratagem.service                                                                    loaded    active   running   IML Stratagem Service
  iml-syslog.service                                                                       loaded    active   running   IML Syslog Service
  iml-update-handler.service                                                               loaded    inactive dead      IML Update Handler
  iml-view-server.service                                                                  loaded    active   running   IML View Server Service
  iml-warp-drive.service                                                                   loaded    active   running   IML Warp Drive Service
```

This used to work occasionally - I've been able to use web UI several times on previous deployments. Then I reprovisioned `adm` machine and now it usually doesn't work.

It turns out it also works in Chrome and in private mode.

I've cleared cookies and disabled all my addons - doesn't help when not in private mode.

**Comment by ip1981** [comment]
Check out console log for something like **"import object field '__wbg_new_eb0c1cd98131d6b3' is not a Function"**. It is likely due to caching. It works in Chrome, because it is first opened in it (with Firefox you already had cached parts), it works in private mode either for the same reason, or because cache is disabled in private mode.

**Comment by utopiabound** [comment]
You can drop cache for the site, and it works.

**Comment by jgrund** [comment]
@mkpankov is there any error in the console?

**Comment by jgrund** [comment]
Beyond running incognito mode, you should be able to bypass this by checking the following box in chrome devtools (when they are open):

![Screen Shot 2019-11-21 at 9 57 18 AM](https://user-images.githubusercontent.com/458717/69349262-76956380-0c45-11ea-8550-ea0986e4e8f5.png)

Or in firefox devtools:

![Screen Shot 2019-11-21 at 10 00 03 AM](https://user-images.githubusercontent.com/458717/69349477-cc6a0b80-0c45-11ea-9a91-53124efc201e.png)

Hopefully when the seed top level app is in place this will no longer be an issue.

**Comment by johnsonw** [comment]
@mkpankov did this resolve the issue?

**Comment by mkpankov** [comment]
Ok so I've been using Private mode now, in case I stumble onto it again and disabling caching won't help, I'll reopen.
